# Параметры сайта
title: Лэндфист
description: > # this means to ignore newlines until next parameter
  Сервис ландшафтных фотоснимков
timezone: Asia/Yekaterinburg

api:
  version: 2.0 alpha1
  date: 06.11.2019

theme: jekyll-theme-midnight # Параметры настройки: https://github.com/pages-themes/midnight
show_downloads: true
urls:
  sasplanet_web: http://www.sasgis.org
  sasplanet_dowload: http://www.sasgis.org/download/
  sasplanet_lps_plugin: https://yadi.sk/d/bMaNtIaIYW_eLA
  landphist_api_docs: https://landphist.azurewebsites.net/api/docs

analytics: 
  google_analytics: UA-69737937-3
  yandex_metrika: 56132614
  
