# Параметры сайта
title: Лэндфист
description: > # this means to ignore newlines until next parameter
  Сервис ландшафтных фотоснимков
timezone: Asia/Yekaterinburg
analytics: 
  google_analytics: UA-69737937-3
  yandex_metrika: 56132614

theme: jekyll-theme-midnight # Параметры настройки: https://github.com/pages-themes/midnight
show_downloads: true
urls:
  sasplanet_web: http://www.sasgis.org
  sasplanet_dowload: http://www.sasgis.org/download/
  sasplanet_lps_plugin: https://yadi.sk/d/bMaNtIaIYW_eLA
