title: Лэндфист
description: > # this means to ignore newlines until next parameter
  Сервис ландшафтных фотоснимков
timezone: Asia/Yekaterinburg

# Параметры настройки: https://github.com/pages-themes/midnight
theme: jekyll-theme-midnight
# google_analytics: 
show_downloads: true
urls:
  sasplanet_web: http://www.sasgis.org
  sasplanet_dowload: http://www.sasgis.org/download/
  sasplanet_lps_plugin: https://yadi.sk/d/bMaNtIaIYW_eLA
